#!/bin/bash

#═══════════════════════════════════════════════════════════════════
#  BOT CASINO 13 - VPS Deployment Script
#═══════════════════════════════════════════════════════════════════

set -e

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "          BOT CASINO 13 - DEPLOYMENT SCRIPT                        "
echo "═══════════════════════════════════════════════════════════════════"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    echo -e "${YELLOW}Warning: Running as root. Consider using a non-root user.${NC}"
fi

#───────────────────────────────────────────────────────────────────
# Step 1: Check/Install Node.js
#───────────────────────────────────────────────────────────────────
echo -e "${GREEN}[1/6] Checking Node.js...${NC}"

if command -v node &> /dev/null; then
    NODE_VERSION=$(node -v)
    echo "  Node.js already installed: $NODE_VERSION"
else
    echo "  Installing Node.js 20.x..."
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    sudo apt-get install -y nodejs
    echo "  Node.js installed: $(node -v)"
fi

#───────────────────────────────────────────────────────────────────
# Step 2: Install dependencies
#───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}[2/6] Installing dependencies...${NC}"
npm install --production
echo "  Dependencies installed."

#───────────────────────────────────────────────────────────────────
# Step 3: Configure .env
#───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}[3/6] Configuring environment...${NC}"

if [ -f .env ]; then
    echo -e "${YELLOW}  .env file already exists.${NC}"
    read -p "  Overwrite? (y/N): " OVERWRITE
    if [[ ! "$OVERWRITE" =~ ^[Yy]$ ]]; then
        echo "  Keeping existing .env"
    else
        rm .env
    fi
fi

if [ ! -f .env ]; then
    echo ""
    echo -e "${YELLOW}  Enter your Polymarket wallet private key:${NC}"
    echo "  (starts with 0x, will be hidden)"
    read -s PRIVATE_KEY
    echo ""

    if [[ ! "$PRIVATE_KEY" =~ ^0x[a-fA-F0-9]{64}$ ]]; then
        echo -e "${RED}  Invalid private key format. Should be 0x + 64 hex characters.${NC}"
        echo "  You can manually create .env later with: nano .env"
    else
        cat > .env << EOF
# BOT CASINO 13 - Environment Variables
# Generated by deploy.sh on $(date)

# Polymarket Wallet Private Key
PRIVATE_KEY=$PRIVATE_KEY

# Optional API keys (add if you have them)
# LUNARCRUSH_API_KEY=
# COINGLASS_API_KEY=
# FINNHUB_API_KEY=

# Logging
LOG_LEVEL=info
EOF
        chmod 600 .env
        echo -e "${GREEN}  .env file created and secured.${NC}"
    fi
fi

#───────────────────────────────────────────────────────────────────
# Step 4: Install PM2
#───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}[4/6] Setting up PM2 process manager...${NC}"

if command -v pm2 &> /dev/null; then
    echo "  PM2 already installed."
else
    echo "  Installing PM2..."
    sudo npm install -g pm2
    echo "  PM2 installed."
fi

#───────────────────────────────────────────────────────────────────
# Step 5: Create PM2 ecosystem file
#───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}[5/6] Creating PM2 configuration...${NC}"

cat > ecosystem.config.cjs << 'EOF'
module.exports = {
  apps: [{
    name: 'botcasino13',
    script: 'src/index.js',
    args: 'run',
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: '500M',
    env: {
      NODE_ENV: 'production'
    },
    // Restart at 00:00 UTC daily (fresh start)
    cron_restart: '0 0 * * *',
    // Logging
    error_file: './logs/error.log',
    out_file: './logs/output.log',
    log_file: './logs/combined.log',
    time: true
  }]
};
EOF

# Create logs directory
mkdir -p logs

echo "  PM2 ecosystem config created."

#───────────────────────────────────────────────────────────────────
# Step 6: Start the bot
#───────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}[6/6] Starting the bot...${NC}"

# Stop if already running
pm2 delete botcasino13 2>/dev/null || true

# Start with ecosystem
pm2 start ecosystem.config.cjs

# Save PM2 process list
pm2 save

# Setup PM2 to start on boot
echo ""
echo "  Setting up auto-start on reboot..."
pm2 startup | tail -1 | bash 2>/dev/null || echo "  Run 'pm2 startup' manually if needed"

#───────────────────────────────────────────────────────────────────
# Done!
#───────────────────────────────────────────────────────────────────
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo -e "${GREEN}          DEPLOYMENT COMPLETE!${NC}"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "  Bot Status:"
pm2 status
echo ""
echo "  Useful commands:"
echo "    pm2 logs botcasino13     - View live logs"
echo "    pm2 status               - Check status"
echo "    pm2 restart botcasino13  - Restart bot"
echo "    pm2 stop botcasino13     - Stop bot"
echo ""
echo "  Manual analysis:"
echo "    node src/index.js        - Run single analysis"
echo ""
echo "  The bot will:"
echo "    - Monitor during London (07:00-10:00 UTC)"
echo "    - Monitor during NY AM (13:00-16:00 UTC)"
echo "    - Auto-restart daily at 00:00 UTC"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
